### ISSUE TITLE
With search term "org file + heading", top level headings ignored

### ISSUE THREAD

**Issue by Maltimore** [nvim-orgmode/telescope-orgmode.nvim#24]
Say I have a file called `abcd.org`:

```
* foo
** f bar oo
```

Now if I do the normal search for headlines and my search term is `foo`, then it will find `* foo`. However, if my search term is `abcd foo` or `abcdfoo` (because the filename is `abcd.org`), then it will not find `* foo` but will match another headline. In this case, it could match `** f bar oo`.

**Comment by seflue** [comment]
Ah, yes. This is a quirk which I put in with a little bit of intension. I switched the order of filename and headline during filtering, because I found myself most often having a headline in mind and then, when the results are too much, filtering this down by the filename. But I didn't switch the order of the columns, because I want to use the fixed column for the filename and had issues, putting this fixed column to the right.

But I acknowledge, that this is a bit counter-intuitive. So thanks for the feedback.

**Comment by seflue** [comment]
For now as a workaround search for fooabcd, which will work.

**Comment by Maltimore** [comment]
I can totally see myself in the situation where I remember the headline first and then when I search for it and I see that there are too many results, I want to add the filename to find the right headline. So in that case I would enter the search terms in the order you described above.
I don't know if it is possible, but it would be great if the order in which I put the search terms for file name, first headline, second headline etc didn't matter at all.

**Comment by Maltimore** [comment]
I just noticed that searching for toplevel headline + second level headline also doesn't work. Is it true then that the only combinations how one can search is

First headline + org file
Second headline + org file
Third headline + org file

etc.? I.e. the following are all not possible:

first headline + second headline
second headline + first headline
org file + first headline
org file + second headline

I could see all of these be relevant. But I don't know how constrained telescope is for this kind of searching.

**Comment by seflue** [comment]
What you expecting might be a nice feature addition, but it's actually not, how it is implemented. The plugin generates a flattened list of all headline titles, no matter of its level. It shows the level, but it doesn't include the parent headline in the base string for filtering.

Actually it would be possible to implement that. The problem I see is the following: You don't want to actually SHOW all those parent headlines, because it is way to long. So you include the parent in the filtering string, but not in the display string. The thing is, that you then get a lot of results, which are unexpected, because the filter you typed is not matched by the entries you see on the screen. It is a double-edged sword.

There are a few of these useability quirks where I am currently reaching the limits of my understanding of Telescope, or indeed the limits of Telescope's capabilities. Finding a well balanced usability that is flexible and powerful to satisfy the advanced user, but doesn't break with the expectations of a beginner, is actually not easy.

I think I'll have to put a bit more brainpower into feature design before I implement an improvement. However, I am very open to good suggestions and constructive discussion.

**Comment by Maltimore** [comment]
Thanks for your detailed thoughts. I think I understand exactly the problems you described. One first idea would be:

In the display string ("Results" window), you only display the org file + the lowest level headline, no matter what the user searched for. This is because the lowest level headline is the most specific to what the user actually wants. And then in the "preview" window on the right, you display the full hierarchy.

I.e., the org file is `abcd.org`:
```
* first
  some text
  more text
** second
   unrelated text
*** third
    text underneath the third headline
```
And the user searches for `abcfithi` (for `abcd.org` `first` `third`, the user omitted `second` but it doesn't matter). So then in the "Results" the display string would be `abcd.org third`. But if the user selects this result, then in the "Preview" window, it displays:

```
* first
** second
*** third
    text underneath the third headline
```
So here the text underneath the third headline is also included such that the user has some more info on the result he found.

**Comment by seflue** [comment]
@Maltimore Thanks for your ideas. In my opinion it is a complete new mode. I am open to review a PR, but I don't see myself implementing this feature. Therefore I close this issue for know.
